/// Flutter icons IconsCustom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsCustom
///      fonts:
///       - asset: fonts/IconsCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsCustom {
  IconsCustom._();

  static const _kFontFam = 'IconsCustom';
  static const String? _kFontPkg = null;

  static const IconData news = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vk = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
